# Generated by Django 5.2.1 on 2025-05-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_receta_activa_receta_porciones_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredienteinsumoelaborado',
            name='ingrediente_elaborado_solo_un_tipo',
        ),
        migrations.AddConstraint(
            model_name='ingredienteinsumoelaborado',
            constraint=models.CheckConstraint(check=models.Q(...), name='ingrediente_elaborado_solo_un_tipo'),
        ),
    ]
